name: CI

on:
  push:
  pull_request:

jobs:
  docker:
    name: Build and test docker image

    strategy:
      matrix:
        nominatim:
          - version: "4.0"
            update_command: docker exec -i nominatim sudo -u nominatim nominatim replication --project-dir /nominatim --once
          - version: "3.7"
            update_command: docker exec -i nominatim sudo -u nominatim nominatim replication --project-dir /nominatim --once

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build docker image
        run: docker build -t nominatim .
        working-directory: ${{ matrix.nominatim.version }}

      - name: Check import with PBF_URL and update
        working-directory: .github/workflows
        run: |-
          # get the data from four days ago to make sure there really are updates to apply
          four_days_ago=`date --date="4 days ago" +%y%m%d`
          docker run -i --rm \
            -e PBF_URL=http://download.geofabrik.de/europe/monaco-${four_days_ago}.osm.pbf \
            -e REPLICATION_URL=http://download.geofabrik.de/europe/monaco-updates/ \
            -p 8001:8080 \
            --name nominatim \
            nominatim &
          sleep 35
          ./assert-non-empty-json "http://localhost:8001/search.php?q=avenue%20pasteur"
          ${{ matrix.nominatim.update_command }}
          ./assert-non-empty-json "http://localhost:8001/search.php?q=avenue%20pasteur"
          docker stop nominatim

      - name: Check import with mount
        working-directory: .github/workflows
        run: |-
          docker run -i --rm \
            -e PBF_URL=http://download.geofabrik.de/europe/monaco-latest.osm.pbf \
            -e REPLICATION_URL=http://download.geofabrik.de/europe/monaco-updates/ \
            -v nominatim-data:/var/lib/postgresql/12/main \
            -p 8002:8080 \
            nominatim &
          sleep 35
          ./assert-non-empty-json "http://localhost:8002/search.php?q=avenue%20pasteur"

      - name: Check import with bind-mount
        working-directory: .github/workflows
        run: |-
          docker run -i --rm \
            -e PBF_URL=http://download.geofabrik.de/europe/monaco-latest.osm.pbf \
            -e REPLICATION_URL=http://download.geofabrik.de/europe/monaco-updates/ \
            -v /tmp/nominatim-data:/var/lib/postgresql/12/main \
            -p 8003:8080 \
            --name nominatim \
            nominatim &
          sleep 35
          ./assert-non-empty-json "http://localhost:8003/search.php?q=avenue%20pasteur"
          docker stop nominatim

      - name: Check container restart and update with bind-mount
        working-directory: .github/workflows
        run: |-
          # get the data from four days ago to make sure there really are updates to apply
          four_days_ago=`date --date="4 days ago" +%y%m%d`
          docker run -i --rm \
            -e PBF_URL=http://download.geofabrik.de/europe/monaco-${four_days_ago}.osm.pbf \
            -e REPLICATION_URL=http://download.geofabrik.de/europe/monaco-updates/ \
            -v /tmp/nominatim-data:/var/lib/postgresql/12/main \
            -p 8004:8080 \
            --name nominatim \
            nominatim &
          sleep 5
          ./assert-non-empty-json "http://localhost:8004/search.php?q=avenue%20pasteur"
          ${{ matrix.nominatim.update_command }}
          ./assert-non-empty-json "http://localhost:8004/search.php?q=avenue%20pasteur"
          docker stop nominatim

      - name: Check import full style
        working-directory: .github/workflows
        run: |-
          docker run -i --rm \
            -e PBF_URL=http://download.geofabrik.de/europe/monaco-latest.osm.pbf \
            -e REPLICATION_URL=http://download.geofabrik.de/europe/monaco-updates/ \
            -e IMPORT_STYLE=full \
            -p 8005:8080 \
            nominatim &
          sleep 35
          ./assert-non-empty-json "http://localhost:8005/search.php?q=hotel%20de%20paris"

      - name: Check import admin style
        working-directory: .github/workflows
        run: |-
          docker run -i --rm \
            -e PBF_URL=http://download.geofabrik.de/europe/monaco-latest.osm.pbf \
            -e REPLICATION_URL=http://download.geofabrik.de/europe/monaco-updates/ \
            -e IMPORT_STYLE=admin \
            -p 8006:8080 \
            nominatim &
          sleep 35
          ./assert-empty-json "http://localhost:8006/search.php?q=hotel%20de%20paris"

      - name: Check import with PBF_PATH
        working-directory: .github/workflows
        run: |-
          wget --cut-dirs=1 -nH -xP /tmp/data http://download.geofabrik.de/europe/monaco-latest.osm.pbf
          docker run -i --rm \
            -e PBF_PATH=/nominatim/data/monaco-latest.osm.pbf \
            -e REPLICATION_URL=http://download.geofabrik.de/europe/monaco-updates/ \
            -v nominatim7-data:/var/lib/postgresql/12/main \
            -v /tmp/data:/nominatim/data \
            -p 8007:8080 \
            --name nominatim \
            nominatim &
          sleep 35
          ./assert-non-empty-json "http://localhost:8007/search.php?q=avenue%20pasteur"
          docker stop nominatim
          docker volume rm nominatim7-data

      - name: Check when REPLICATION_URL is blank
        working-directory: .github/workflows
        run: |-
          docker run -i --rm \
            -e PBF_URL=http://download.geofabrik.de/europe/monaco-latest.osm.pbf \
            -p 8008:8080 \
            nominatim &
          sleep 35
          ./assert-non-empty-json "http://localhost:8008/search.php?q=avenue%20pasteur"

      - name: Login to DockerHub
        if: ${{ github.ref == 'refs/heads/master' && github.repository_owner == 'mediagis' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push production docker image to Dockerhub
        if: ${{ github.ref == 'refs/heads/master' && github.repository_owner == 'mediagis' }}
        run: |-
          docker buildx build --platform linux/amd64,linux/arm64 --push \
             -t mediagis/nominatim:${{ matrix.nominatim.version }} \
             -t mediagis/nominatim:${{ matrix.nominatim.version }}-${{ github.sha }} .
        working-directory: ${{ matrix.nominatim.version }}